# Generated by Django 5.2 on 2025-05-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Talent Verify Admin'), ('company', 'Company User'), ('verifier', 'Verification User')], default='company', max_length=10),
        ),
    ]
