# Generated by Django 5.2 on 2025-05-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_employee_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_department_per_company'),
        ),
    ]
